[package]
name = "pistatus"
version = "0.1.0"
authors = ["pi"]

[dependencies]
env_logger = "*"
log = "0.4.5"
sensehat-screen = { version = "=0.2.0" }
reqwest = "0.9.3"
serde = "1.0.80"
serde_derive = "1.0.80"
